### ISSUE TITLE
Version Formatting Error

### ISSUE THREAD

**Issue by ihtarlik** [eliben/gemini-cli#5]
When running the install command on Raspberry Pi OS (Debian 12 Bookworm, go version go1.19.8 linux/arm64), I get the following error:

go: github.com/eliben/gemini-cli@latest (in github.com/eliben/gemini-cli@v0.7.0): go.mod:3: invalid go version '1.22.2': must match format 1.23

Is this project compatible with this version of Go? Can it be ported for use on Pis?

**Comment by eliben** [comment]
The core issue is your very old version of Go - 1.19.8 - this version is no longer supported by the Go team and you ought to upgrade it to a supported version.

(https://go.dev/doc/devel/release#policy)
